name: CI

on:
  push:
    branches: ["**"]
  pull_request:
    branches: [main]

jobs:
  lint-and-typecheck:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Lint @apps/web
        run: cd apps/web && bun run lint

      - name: TypeCheck @apps/web
        run: cd apps/web && bun run ts

      - name: Lint @apps/hyperdb
        run: cd apps/hyperdb && bun run lint

      - name: TypeCheck @apps/hyperdb
        run: cd apps/hyperdb && bun run ts

      - name: Lint @apps/api
        run: cd apps/api && bun run lint

      - name: TypeCheck @apps/api
        run: cd apps/api && bun run ts

      - name: Lint @apps/slices
        run: cd apps/slices && bun run lint

      - name: TypeCheck @apps/slices
        run: cd apps/slices && bun run ts
